### ISSUE TITLE
EmberJS-приложение клиент к серверу

### ISSUE THREAD

**Issue by DeTeam** [DeTeam/hstalk-monitor#1]
Нужно дописать клиентское приложение для отображения инфы в браузере.
Основная структура сейчас есть, нехватает:
- Отображения нужной информации о сервере в общем 
- Отображения нужной информации о конкретном тьюбе
- Отображения нужно информации о конкретном джобе из тьюба

В каждом из пунктов, возможно, понадобится слать какие-то дополнительные ключи-значения с сервера, это стоит обговорить.

Данные пушатся с сервера раз в 5 секунд. 
Установка - см. INSTALL

Known Issue - если перейти сразу в какой-то тьюб (например, после перезагрузки страницы), то не подгрузится инфа о имеющихся тьюбах. Возможно стоит пересмотреть подгрузку состояний (сделать так, чтобы переход в состояние с включенным тьюбом происходил только после 1 пуша general info)

**Comment by oruen** [comment]
Не совсем понятно, что называется "нужной" информацией.

> Отображения нужной информации о конкретном тьюбе

сделано

> Known Issue

Более не issue

**Comment by oruen** [comment]
> Отображения нужной информации о сервере в общем

done

> Отображения нужно информации о конкретном джобе из тьюба

решили не делать
